site_name: paperwurks
site_description: Paperwurks 2025
repo_url: https://github.com/Paperwurks/paperwurks-python-backend
site_dir: site
copyright: Copyright &copy; 2020, <a href="https://github.com/Paperwurks">Paperwurks</a>.
dev_addr: 0.0.0.0:8001

nav:
  - Home: 'index.md'
  - API:
    - Authentication: 'api/authentication.md'
    - Users: 'api/users.md'
